import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [isExiting, setIsExiting] = useState(false);

  const handleNavigation = async (e: React.MouseEvent<HTMLAnchorElement, MouseEvent>, href: string) => {
    e.preventDefault();
    setIsExiting(true);
    setTimeout(() => {
      void router.push(href);
    }, 500);
  };

  return (
    <>
      <Head>
        <title>JUST SAP IT! Interview Task</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white ${
          isExiting ? "page-exit-active" : "page-enter-active"
        }`}
      >
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">JUST SAP IT!</span>
            <br />
            <span>Interview</span> Task
          </h1>
          <div className="flex flex-col items-center">
            <h2 className="text-2xl font-bold">Welcome to the Todo App</h2>
            <Link
              href="/todos"
              onClick={(e) => handleNavigation(e, "/todos")}
              className="relative mt-6 px-6 py-3 text-lg font-semibold text-white bg-transparent border border-white rounded-lg shadow-md transition-all duration-300 ease-in-out hover:bg-white hover:text-[#2e026d] hover:shadow-xl hover:scale-105"
            >
              Go to Todos
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
