// More information can be found in the Next.js docs (make sure pages router is selected)
// https://nextjs.org/docs

import Head from 'next/head';
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>JUST SAP IT! Interview Task</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white'>
        <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16'>
          <h1 className='text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]'>
            <span className='text-[hsl(280,100%,70%)]'>JUST SAP IT!</span>
            <br />
            <span>Interview</span> Task
            <div className="flex flex-col items-center">
        <h1 className="text-2xl font-bold">Welcome to the Todo App</h1>
        <Link href="/todos" className="mt-4 px-4 py-2 bg-blue-500 text-white rounded">
          Go to Todos
        </Link>
      </div>
          </h1>
        </div>
      </main>
    </>
  );
}
